import { MemoryStore } from './store.js';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

const GENERATORS = {
  claude: (memories) => {
    const lines = ['# Project Memory (auto-generated by kodo)', ''];
    for (const m of memories) {
      lines.push(`## [${m.type.toUpperCase()}] ${m.tags.length ? `(${m.tags.join(', ')})` : ''}`);
      lines.push(m.content);
      lines.push('');
    }
    return { path: '.claude/settings/memory.md', content: lines.join('\n') };
  },
  cursor: (memories) => {
    const lines = ['# Project Memory (auto-generated by kodo)', ''];
    for (const m of memories) {
      lines.push(`## ${m.type}: ${m.tags.join(', ') || 'general'}`);
      lines.push(m.content);
      lines.push('');
    }
    return { path: '.cursor/rules/kodo-memory.md', content: lines.join('\n') };
  },
  kiro: (memories) => {
    const frontmatter = [
      '---',
      'inclusion: auto',
      'name: kodo-memory',
      'description: "Project memory — conventions, patterns, and learned preferences from kodo"',
      '---',
      '',
      '# Project Memory',
      '',
    ];
    for (const m of memories) {
      frontmatter.push(`## [${m.type.toUpperCase()}]`);
      if (m.tags.length) frontmatter.push(`Tags: ${m.tags.join(', ')}`);
      frontmatter.push(m.content);
      frontmatter.push('');
    }
    return { path: '.kiro/steering/kodo-memory.md', content: frontmatter.join('\n') };
  },
  codex: (memories) => {
    const lines = ['# Project Memory (auto-generated by kodo)', ''];
    for (const m of memories) {
      lines.push(`- [${m.type}] ${m.content.replace(/\n/g, ' ').slice(0, 200)}`);
    }
    return { path: '.codex/memory.md', content: lines.join('\n') };
  },
};

export function exportMemories(projectDir, agents = ['claude', 'cursor', 'kiro', 'codex']) {
  const store = new MemoryStore(projectDir);
  const memories = store.search(null, { limit: 100 });
  store.close();
  const results = [];
  for (const agent of agents) {
    const gen = GENERATORS[agent];
    if (!gen) continue;
    const { path: relPath, content } = gen(memories);
    const fullPath = join(projectDir, relPath);
    const dir = join(fullPath, '..');
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, content);
    results.push({ agent, path: fullPath, count: memories.length });
  }
  return results;
}
